export const participantData = [
  {
    key: "1",
    participant: "James Toone",
    level: 1,
    notStarted: 0,
    notAchieved: 0,
    workingOn: 0,
    completed: 0,
    achieved: 8,
    levelCompleted: true,
  },
  {
    key: "2",
    participant: "Sarah Johnson",
    level: 1,
    notStarted: 1,
    notAchieved: 0,
    workingOn: 0,
    completed: 5,
    achieved: 2,
  },
  {
    key: "3",
    participant: "Robert Smith",
    level: 1,
    notStarted: 1,
    notAchieved: 0,
    workingOn: 2,
    completed: 4,
    achieved: 1,
  },
  {
    key: "4",
    participant: "Jessica Davis",
    level: 1,
    notStarted: 1,
    notAchieved: 0,
    workingOn: 2,
    completed: 2,
    achieved: 3,
  },
  {
    key: "5",
    participant: "Michael Miller",
    level: 1,
    notStarted: 1,
    notAchieved: 0,
    workingOn: 2,
    completed: 1,
    achieved: 4,
  },
  {
    key: "6",
    participant: "Emily Clark",
    level: 1,
    notStarted: 0,
    notAchieved: 0,
    workingOn: 2,
    completed: 0,
    achieved: 6,
  },
  {
    key: "7",
    participant: "John White",
    level: 1,
    notStarted: 0,
    notAchieved: 0,
    workingOn: 0,
    completed: 0,
    achieved: 8,
  },
  {
    key: "8",
    participant: "Emma Lewis",
    level: 1,
    notStarted: 1,
    notAchieved: 0,
    workingOn: 2,
    completed: 1,
    achieved: 4,
  },
  {
    key: "9",
    participant: "William Green",
    level: 2,
    notStarted: 1,
    notAchieved: 0,
    workingOn: 4,
    completed: 1,
    achieved: 2,
  },
  {
    key: "10",
    participant: "Sophia Brown",
    level: 2,
    notStarted: 1,
    notAchieved: 0,
    workingOn: 2,
    completed: 1,
    achieved: 4,
  },
  {
    key: "11",
    participant: "Jacob Black",
    level: 2,
    notStarted: 1,
    notAchieved: 0,
    workingOn: 2,
    completed: 1,
    achieved: 4,
  },
  {
    key: "12",
    participant: "Olivia Taylor",
    level: 2,
    notStarted: 1,
    notAchieved: 0,
    workingOn: 5,
    completed: 1,
    achieved: 1,
  },
  {
    key: "13",
    participant: "Lucas Turner",
    level: 1,
    notStarted: 1,
    notAchieved: 0,
    workingOn: 2,
    completed: 1,
    achieved: 4,
  },
  {
    key: "14",
    participant: "Mia Anderson",
    level: 1,
    notStarted: 1,
    notAchieved: 0,
    workingOn: 2,
    completed: 1,
    achieved: 4,
  },
];
