export const skillData = [
  {
    key: "1",
    skill: "Enter the water safely",
    level: 1,
    notStarted: 0,
    notAchieved: 0,
    workingOn: 0,
    completed: 0,
    achieved: 8,
  },
  {
    key: "2",
    skill:
      "Move forward for a distance of 5 metres, feet may be on or off the floor",
    level: 1,
    notStarted: 0,
    notAchieved: 0,
    workingOn: 0,
    completed: 0,
    achieved: 8,
  },
  {
    key: "3",
    skill:
      "Move backwards for a distance of 5 metres, feet may be on or off the floor",
    level: 1,
    notStarted: 1,
    notAchieved: 0,
    workingOn: 0,
    completed: 1,
    achieved: 6,
  },
  {
    key: "4",
    skill:
      "Move sideways for a distance of 5 metres, feet may be on or off the floor",
    level: 1,
    notStarted: 1,
    notAchieved: 0,
    workingOn: 2,
    completed: 2,
    achieved: 5,
  },
  {
    key: "5",
    skill: "Scoop the water and wash the face",
    level: 1,
    notStarted: 1,
    notAchieved: 0,
    workingOn: 2,
    completed: 1,
    achieved: 4,
  },
  {
    key: "6",
    skill: "Be comfortable with water showered from overhead",
    level: 1,
    notStarted: 0,
    notAchieved: 2,
    workingOn: 2,
    completed: 1,
    achieved: 3,
  },
  {
    key: "7",
    skill:
      "Move from a flat floating position on the back and return to standing",
    level: 1,
    notStarted: 1,
    notAchieved: 0,
    workingOn: 4,
    completed: 1,
    achieved: 2,
  },
  {
    key: "8",
    skill:
      "Move from a flat floating position on the front and return to standing",
    level: 1,
    notStarted: 1,
    notAchieved: 0,
    workingOn: 4,
    completed: 1,
    achieved: 0,
  },
  {
    key: "9",
    skill: "Push and glide in a flat position on the front from a wall",
    level: 2,
    notStarted: 1,
    notAchieved: 0,
    workingOn: 6,
    completed: 1,
    achieved: 0,
  },
  {
    key: "10",
    skill: "Push and glide in a flat position on the back from a wall",
    level: 2,
    notStarted: 1,
    notAchieved: 0,
    workingOn: 6,
    completed: 1,
    achieved: 0,
  },
  {
    key: "11",
    skill: "Give examples of two pool rules",
    level: 2,
    notStarted: 1,
    notAchieved: 0,
    workingOn: 6,
    completed: 1,
    achieved: 0,
  },
  {
    key: "12",
    skill: "Exit the water safely",
    level: 2,
    notStarted: 1,
    notAchieved: 0,
    workingOn: 6,
    completed: 1,
    achieved: 0,
  },
];
